### ISSUE TITLE
[Bug] Unexpected behavior with CondaActivate, not recognize conda binary inside built-in vim terminal

### ISSUE THREAD

**Issue by hungpham3112** [ubaldot/vim-conda-activate#3]
## Step to reproduce:
- create an file test.vim 
```
if has('win32')
    call plug#begin(has('nvim') ? stdpath('data') . '/plugged' : '~/vimfiles/plugged')
else
    call plug#begin(has('nvim') ? stdpath('data') . '/plugged' : '~/.vim/plugged')
endif
Plug 'https://github.com/ubaldot/vim-conda-activate', {'for': ['python', 'julia']}
call plug#end()
```
- run `vim -u test.vim` to load the setting
- `:PlugInstall` to install vim-conda-activate
- `:vert term` to open the terminal and check if conda exist then close terminal without leaving vim
- `:e /python/file` to edit the python file
- `:CondaActivate` an select a random env
- `:vert term` to check conda will not exist.

## Additional information:
- `OS`: Windows 11
- `Terminal`: Allacritty
- `vim-conda-activate` --version: latest

## My thought: 
Activating the command in vim-conda-activate so $PATH will be changed that leads to not recognize conda binary.

**Comment by ubaldot** [comment]
Hum, I cannot test it now on Windows, but I did in MacOSX and there is not that problem, but it could be that problem in Windows. And your thoughts make sense.

`conda` binary is typically in some `.../condabin` folder, typically in `~/Miniconda3/condabin` or something like that. You can check on your system. 
Could you please verify if the output of `echo $PATH` from different places makes such a `condabin` folder to disappear?

**Comment by ubaldot** [comment]
I am looking into the issue and it seems that the issue appears when you start vim from `cmd.exe.` I tried and the problems does not seem to be if you start vim from `Powershell`. Do you confirm?

**Comment by hungpham3112** [comment]
Yes it works. I tested on cmd.exe and cmd.exe is problem. But still need to check if it working on others terminal or not( gnome-term, kde-term..).

**Comment by ubaldot** [comment]
@hungpham3112  Any news on this issue? :)

**Comment by hungpham3112** [comment]
I tested on Pop-OS (Ubuntu-based) 22.04 in `allacritty ` terminal with `conda 23.5.0` and didn't see any error. I think the problem solved. Thanks for your hard work.
